// Declarative system diagrams, rendered by components/Diagram.tsx.
// Coordinates are in a 960-wide viewBox. `notes` is what the reader sees when
// they hover or tap a node — written as "what it does and why it exists".
// Amber (guard) boxes are the rules that hold when people or systems misbehave.

export type NodeKind = "agent" | "service" | "store" | "external" | "guard" | "human" | "ui" | "tool";

export type DNode = { id: string; label: string; sub?: string; x: number; y: number; w?: number; h?: number; kind: NodeKind };
export type DEdge = { from: string; to: string; label?: string; dashed?: boolean };
export type DiagramSpec = { w: number; h: number; nodes: DNode[]; edges: DEdge[]; notes: Record<string, string> };

export const diagrams: Record<string, DiagramSpec> = {
  "jit-pivot": {
    w: 900,
    h: 400,
    nodes: [
      { id: "retailer", label: "Shopkeeper", sub: "orders in the evening", x: 30, y: 170, kind: "human" },
      { id: "app", label: "Buyer app", sub: "single seller · no per-brand MOV", x: 240, y: 80, kind: "ui" },
      { id: "fee", label: "₹75 fee, waived ≥ ₹500", sub: "shipped as one flag", x: 240, y: 260, kind: "guard" },
      { id: "jit", label: "JIT console", sub: "one PO per brand, that night", x: 450, y: 170, kind: "service" },
      { id: "brands", label: "Brands", sub: "our vehicle collects next morning", x: 690, y: 40, kind: "external" },
      { id: "warehouse", label: "Own warehouse", sub: "receive · putaway · pick · pack", x: 690, y: 170, kind: "service" },
      { id: "fleet", label: "Own fleet", sub: "dispatch · doorstep", x: 690, y: 300, kind: "service" },
      { id: "breach", label: "Breach queue", sub: "3–4 day promise", x: 450, y: 320, kind: "guard" },
    ],
    edges: [
      { from: "retailer", to: "app" },
      { from: "app", to: "fee", label: "cart" },
      { from: "fee", to: "jit", label: "order" },
      { from: "jit", to: "brands", label: "PO per brand" },
      { from: "brands", to: "warehouse", label: "pickup" },
      { from: "warehouse", to: "fleet" },
      { from: "jit", to: "breach", dashed: true, label: "past target" },
      { from: "fleet", to: "retailer", dashed: true, label: "next-day delivery" },
    ],
    notes: {
      retailer: "A kirana owner in Delhi or Gurgaon. Before the pivot, a ₹900 basket across three brands was blocked by three separate ₹300 minimums. After it, one seller and no minimum.",
      app: "The buyer app became a single-seller marketplace: everything resolves to Badho Wholesale. Brand minimums disappeared from the cart entirely.",
      fee: "The replacement for per-brand minimums: a flat ₹75 delivery fee waived above ₹500, shipped as a single flag so a buyer can never end up with neither a minimum nor a fee.",
      jit: "Just-in-time, literally. Orders arrive in the evening; the console consolidates one purchase order per brand and pushes it that night. We never hold stock. This is the piece the operating document specified step by step.",
      brands: "The same brands we used to forward orders to. Now they are suppliers, and their minimum is met at our volume where it is trivial.",
      warehouse: "Layout and zoning, inbound receiving and putaway, pick-pack-dispatch, and the exception path when a brand short-ships, all written before the first delivery. Twelve days from document to first order.",
      fleet: "Our own vehicles, with driver allocation from the delivery-as-a-service stack. Serviceability was deliberately cut to two cities: density is the whole model.",
      breach: "Every order is checked against the delivery promise. Anything past target surfaces in a queue with its age, so the oldest order is always the next one worked.",
    },
  },

  "contribution-turnaround": {
    w: 900,
    h: 420,
    nodes: [
      { id: "order", label: "Courier order", sub: "₹708, 4.3 kg, zone E: ₹282 freight", x: 30, y: 180, w: 190, kind: "store" },
      { id: "courier", label: "3PL courier", sub: "reweighs, charges the difference", x: 280, y: 40, kind: "external" },
      { id: "claims", label: "Claims service", sub: "24h window · sorter photo as proof", x: 500, y: 40, kind: "service" },
      { id: "dedupe", label: "De-dupe guard", sub: "every open ticket on the waybill", x: 720, y: 40, kind: "guard" },
      { id: "ledger", label: "Freight ledger", sub: "cost captured per order", x: 280, y: 180, kind: "store" },
      { id: "returns", label: "Returns stack", sub: "prepaid-only · address check · promise", x: 500, y: 180, w: 190, kind: "guard" },
      { id: "retailer", label: "Shopkeeper", sub: "reminder call · doorstep triage", x: 720, y: 180, kind: "human" },
      { id: "brand", label: "Brand statement", sub: "line-item deductions, not a mystery", x: 280, y: 320, kind: "ui" },
      { id: "pnl", label: "Contribution / order", sub: "−₹196 → +₹36", x: 500, y: 320, kind: "store" },
    ],
    edges: [
      { from: "order", to: "courier" },
      { from: "courier", to: "claims", label: "weight discrepancy" },
      { from: "claims", to: "dedupe" },
      { from: "dedupe", to: "courier", dashed: true, label: "claim filed" },
      { from: "order", to: "ledger" },
      { from: "ledger", to: "brand" },
      { from: "order", to: "returns", label: "on delivery attempt" },
      { from: "returns", to: "retailer" },
      { from: "ledger", to: "pnl" },
      { from: "returns", to: "pnl", dashed: true, label: "RTO 42.6% → 21.4%" },
    ],
    notes: {
      order: "The order that framed the problem: ₹708.50 of goods, ₹282 of freight plus ₹25.50 COD fee, roughly 43% of order value spent shipping it.",
      courier: "Third-party couriers on the intercity model. They systematically reweighed parcels and billed the difference; every one of those was recoverable, but only inside a 24-hour priority window.",
      claims: "Detects the weight discrepancy, checks nobody has already raised it, and files the claim with the courier's own sorter photograph as evidence. 378 claims and 362 tickets on one representative day. Built by the automation team to my requirement.",
      dedupe: "The guard rail: de-duplicates against every open ticket on that waybill, not just its own, so it can never double-file on top of a human. Judgement stayed with people; the deadline went to a system.",
      ledger: "Courier cost, handling and weight deductions captured per order. You cannot fix a cost nobody can see.",
      returns: "Automatic prepaid-only after a single return (reinstatement by manual review), address validation at checkout, a zone-wise delivery promise paying ₹50 when missed, doorstep-refusal triage, reminder calls on the day. 34 of 42 fulfilment features were specced by me.",
      retailer: "The person whose parcel took 28 days at the p90 in January and 10 days by June. He does not experience a median.",
      brand: "Brands see deductions as a line-item breakup instead of unexplained numbers on a settlement. Disputes drop when the cost is legible.",
      pnl: "Contribution per completed order, from the company P&L: Feb −₹196, Apr −₹25, Jun −₹18, Jul +₹36.",
    },
  },

  "whatsapp-channel": {
    w: 900,
    h: 440,
    nodes: [
      { id: "base", label: "Buyer base", sub: "1,167,517 people", x: 30, y: 30, kind: "store" },
      { id: "waterfall", label: "Cohort waterfall", sub: "7 rules · first match wins", x: 250, y: 30, kind: "service" },
      { id: "gate", label: "Serviceability gate", sub: "pincode inner-join before any send", x: 470, y: 30, kind: "guard" },
      { id: "router", label: "Template router", sub: "utility vs marketing · ~7× gap", x: 470, y: 170, kind: "guard" },
      { id: "sender", label: "Self-hosted sender", sub: "₹0.145 → ₹0.115 a message", x: 250, y: 170, kind: "service" },
      { id: "meta", label: "Meta WhatsApp API", sub: "the platform we now talk to directly", x: 30, y: 170, kind: "external" },
      { id: "retailer", label: "Shopkeeper", sub: "taps, or sends a photo of a list", x: 30, y: 320, kind: "human" },
      { id: "app", label: "Buyer app", sub: "deep link or Play Store install", x: 250, y: 320, kind: "ui" },
      { id: "attribution", label: "Attribution rule", sub: "same-day window", x: 470, y: 320, kind: "guard" },
      { id: "report", label: "June report", sub: "2.60× ROAS · ₹9.60 an install", x: 690, y: 320, kind: "ui" },
      { id: "agent", label: "Sales agent", sub: "cannot place orders", x: 690, y: 170, kind: "agent" },
    ],
    edges: [
      { from: "base", to: "waterfall" },
      { from: "waterfall", to: "gate" },
      { from: "gate", to: "router" },
      { from: "router", to: "sender" },
      { from: "sender", to: "meta" },
      { from: "meta", to: "retailer", label: "message" },
      { from: "retailer", to: "app", label: "click" },
      { from: "app", to: "attribution", label: "open / install" },
      { from: "attribution", to: "report" },
      { from: "retailer", to: "agent", dashed: true, label: "photo of a list" },
    ],
    notes: {
      base: "Every buyer who ever signed up, installed or ordered. Most of them never ordered, which is why the never-ordered pool is banded by how long they have been gone, down to the 73,473 who installed and never opened the app.",
      waterfall: "Each person lands in exactly one of seven cohorts, first matching rule wins, so the set is mutually exclusive and exhaustive by construction. A live cart outranks a past order.",
      gate: "Messaging someone we cannot deliver to spends money and template quota to annoy them. Every cohort is inner-joined to pincode serviceability first.",
      router: "Meta prices a utility template far below a marketing one: ₹2,885 for 19,894 utility sends against ₹16,811 for 15,423 marketing sends on one campaign. Routing transactional traffic correctly was the larger half of the saving. When Meta rescanned and reclassified 15,398 conversations, it cost ₹14,551.",
      sender: "We were paying a vendor ₹0.145 a message to sit in front of Meta's own API. Moving in-house took it to ₹0.115 on ~169,000 messages a month, and removed a dependency that had already cut us off once over an unpaid invoice.",
      meta: "The WhatsApp Business platform itself. Its template categories and rescans are the variable cost you do not control.",
      retailer: "Many shopkeepers would not tap a link at all. They photographed a handwritten order or typed it in Hinglish. Wonderful intent, impossible to scale with two people on a desk.",
      app: "The app already normalised both entry paths, deep link and fresh install, into one field. Our queries were reading the other one, so 117 buyers were visible out of 537 real.",
      attribution: "Credit an order only if the WhatsApp touch was the same day: 647 orders and 2.60× in June on that rule.",
      report: "The June report: ₹9.60 an install, 2.60× ROAS, and the unit-economics rule for the channel: spend continues while the return clears the take-rate breakeven.",
      agent: "The first working version was mine: orchestrator, prompt layer, messaging, auth and policy engine, committed in one sitting with a handover document. The AI pod owned it from day three. It is blocked from placing orders at the tool layer, so it can never claim to have placed one.",
    },
  },

  "move-it-daas": {
    w: 900,
    h: 420,
    nodes: [
      { id: "distributor", label: "Distributor", sub: "owns trucks, hires drivers", x: 30, y: 60, kind: "human" },
      { id: "book", label: "Book a truck", sub: "7 days ahead · ₹1,400–2,000/day", x: 250, y: 60, kind: "ui" },
      { id: "invoice", label: "Invoice photo", sub: "10–50 drops in seconds", x: 250, y: 190, kind: "agent" },
      { id: "addr", label: "Address lock", sub: "phone + geo-fence, once per shop", x: 470, y: 190, kind: "guard" },
      { id: "route", label: "Route", sub: "planned automatically, no helper", x: 690, y: 190, kind: "service" },
      { id: "otp", label: "Code from both sides", sub: "proof checked against location", x: 690, y: 60, kind: "guard" },
      { id: "cash", label: "Cash to his bank", sub: "matched digitally, same day", x: 690, y: 320, w: 180, kind: "guard" },
      { id: "fail", label: "Named failure reasons", sub: "tallied, sent to his sales team", x: 470, y: 320, w: 180, kind: "store" },
      { id: "cost", label: "₹1,360 → ₹1,612", sub: "what a truck-day actually earned", x: 30, y: 320, w: 180, kind: "external" },
    ],
    edges: [
      { from: "distributor", to: "book" },
      { from: "distributor", to: "invoice", label: "photo" },
      { from: "invoice", to: "addr" },
      { from: "addr", to: "route" },
      { from: "route", to: "otp" },
      { from: "otp", to: "cash", label: "collected" },
      { from: "route", to: "fail", dashed: true, label: "not delivered" },
      { from: "cost", to: "distributor", dashed: true, label: "why he switches" },
    ],
    notes: {
      distributor: "A distributor who owns his own truck pays ₹53,500 to ₹64,500 a month for it whether goods move or not: driver, instalment, fuel, repairs, and about ₹3 lakh simply parked in the vehicle. Forty-eight of them were paying us by July 2026.",
      book: "Booked up to seven days ahead for an eight-hour duty at ₹1,400 to ₹2,000 a truck a day. No lease and nothing to pay on idle days, which matters because this trade is seasonal: a fixed fleet is too small in festival months and sits unused for the rest.",
      invoice: "The order enters as a photograph of the invoice and all ten to fifty drops are set up in seconds. Competitors ask the distributor to integrate his accounting software, which is slow and rarely adopted, or to type the drops in during the morning loading rush, which nobody does.",
      addr: "Small shops have no usable address, which is why other services fail to find them. After the first successful delivery we lock the shop to its phone number, derive the location from the address, and verify it against where the driver actually stood. Over five months that built a map of more than 5,000 shops.",
      route: "The round is planned by software. With a normal vendor the distributor either sits and plans it himself or sends a helper or salesman along in the truck, which is a cost every day.",
      otp: "A code that both people hold, and a photograph only accepted once the driver's location checks out. Proof on every order rather than on the disputed ones.",
      cash: "Normally the owner waits until late at night to receive the cash and match it to his bills. Here the money goes to his own bank account and goods and cash are reconciled digitally the same day, so any member of staff can do the handover.",
      fail: "Shop closed, refused, wrong address, payment not ready. A closed list rather than free text, counted and sent back to his sales team, so a failed delivery becomes something they can act on. A second attempt is priced, not absorbed.",
      cost: "The sale was an argument about his money: a trip on his own truck against a trip on ours, nothing paid on idle days, and capital released from a vehicle. On the price side, a three-wheeler truck-day earned ₹1,360 in May and ₹1,612 by September, and fee income was ₹21.5 lakh on ₹18.95 crore of goods, a take of about 1.1%.",
    },
  },

  "vernacular-search": {
    w: 900,
    h: 400,
    nodes: [
      { id: "shopkeeper", label: "Shopkeeper", sub: "“sarso tel” · “all out” · “meggi”", x: 30, y: 170, kind: "human" },
      { id: "search", label: "Search", sub: "Hindi labels at equal weight", x: 250, y: 170, kind: "service" },
      { id: "rank", label: "Exact-first ranking", sub: "then looser · popularity breaks ties", x: 470, y: 40, kind: "guard" },
      { id: "synonyms", label: "Synonym table", sub: "699,684 rows on 32,536 roots", x: 470, y: 250, kind: "store" },
      { id: "catalogue", label: "Catalogue titles", sub: "“Fortune Kachi Ghani … 1L Pouch”", x: 690, y: 40, kind: "store" },
      { id: "generator", label: "Synonym generator", sub: "LLM · four categories", x: 690, y: 170, kind: "agent" },
      { id: "precision", label: "Stay-specific rule", sub: "toor dal → arhar dal, not dal", x: 690, y: 300, kind: "guard" },
      { id: "events", label: "Search events", sub: "what buyers actually typed", x: 250, y: 320, kind: "store" },
    ],
    edges: [
      { from: "shopkeeper", to: "search", label: "query" },
      { from: "search", to: "rank" },
      { from: "search", to: "synonyms", label: "expands" },
      { from: "catalogue", to: "generator" },
      { from: "generator", to: "precision" },
      { from: "precision", to: "synonyms" },
      { from: "search", to: "events" },
      { from: "events", to: "generator", dashed: true, label: "learning loop" },
    ],
    notes: {
      shopkeeper: "Tier-2 and tier-3 kirana owners typing Hindi in Roman script, phonetically, with typos, and by brand rather than product. A competitor's brand name is often the category name in their head.",
      search: "The product search after a third-party vendor was ripped out seven weeks in. Hindi labels are indexed at equal weight to English so the multilingual catalogue work feeds search directly.",
      rank: "A shopkeeper restocking a known item wants that item, not a helpful selection of similar ones. Exact match first, then progressively looser, popularity as the tie-break.",
      synonyms: "The asset: 699,684 synonyms on 32,536 root words, 21.5 per concept. A static list would have been a fraction of that and would have aged.",
      catalogue: "Messy product titles reduced by a language model to their core unit. Pack size is noise, but packaging that is the product (a jute bag) must survive.",
      generator: "Transliterations (jeera → cumin), colloquial trade terms (“kachua chap” → mosquito coils), phonetic typos (biskut), and genericised brands (surf → detergent). The fourth is the commercial one: a competitor's brand finds our stock.",
      precision: "One rule stops the layer collapsing into mush. An early version matched hair oil to motor oil; the fix was a tighter prompt and an accuracy pass, not more fuzziness.",
      events: "Every real search emits an event. The words the shopkeeper typed feed back into the generator, so the vocabulary compounds and the terms we never thought of arrive on their own.",
    },
  },

  "restaurant-tech-gtm": {
    w: 900,
    h: 400,
    nodes: [
      { id: "outbound", label: "Outbound", sub: "60+ brands · cold email · Apollo", x: 30, y: 40, kind: "service" },
      { id: "pricing", label: "Pricing architecture", sub: "rent or own · per kiosk / store / chain", x: 30, y: 200, w: 190, kind: "store" },
      { id: "chain", label: "Restaurant chain", sub: "Taco Bell · Herfy · DOKA", x: 270, y: 120, kind: "human" },
      { id: "contract", label: "Contract & redlines", sub: "six of seven accepted", x: 490, y: 30, kind: "guard" },
      { id: "renewal", label: "Renewal", sub: "110 → 112 SAR · 17.65% gross-up", x: 710, y: 30, kind: "store" },
      { id: "estate", label: "Kiosk estate", sub: "34 + 79 live kiosks", x: 490, y: 160, kind: "ui" },
      { id: "pos", label: "POS partners", sub: "Petpooja · GoFrugal · POSIST", x: 710, y: 160, kind: "external" },
      { id: "report", label: "Weekly report", sub: "revenue · uptime, and what it missed", x: 490, y: 300, kind: "ui" },
    ],
    edges: [
      { from: "outbound", to: "chain" },
      { from: "pricing", to: "chain", label: "proposal" },
      { from: "chain", to: "contract" },
      { from: "contract", to: "renewal" },
      { from: "chain", to: "estate", label: "go-live" },
      { from: "estate", to: "pos", label: "price sync" },
      { from: "estate", to: "report" },
      { from: "report", to: "chain", dashed: true, label: "weekly" },
    ],
    notes: {
      outbound: "Where I started in January 2024: cold email, LinkedIn and WhatsApp outreach, demo booking, an Apollo lead database, two junior interns from April. Sixty-plus brands reached; a handful became paying clients.",
      pricing: "Subscription (₹35,000 setup, ₹1,500–2,500 per kiosk per month) against an ownership buyout (₹2.5–2.75 lakh, client owns the code); enterprise by store count at ₹4–5 lakh a month. Authored for seven QSR brands.",
      chain: "Taco Bell India (34 kiosks, 19 malls, eleven store mailboxes escalating to me directly), Herfy in Saudi Arabia (79 kiosks, inherited, defended through three renewals), DOKA in Riyadh (nine branches, cold-pitched and signed at ~$7,000).",
      contract: "Herfy's counsel returned seven changes. I accepted six that cost nothing and refused the one that split billing into two cycles, because we funded infrastructure upfront against that invoice. The six concessions are what made the refusal credible.",
      renewal: "A two-riyal rise after fifteen months at 110: anchor on the absolute change, show the cost absorbed, benchmark the 5–10% norm, concede from your own opening. The 15% withholding-tax dispute resolved by grossing the invoice up 17.65%, the figure that leaves the net whole.",
      estate: "The live kiosks I was responsible for keeping up: promotional go-lives, refunds order by order, invoices issued and voided, the payment-reminder feature specified and shipped.",
      pos: "Integrations are how a small software company reaches chains it cannot sell to directly. Formal registrations with GoFrugal and Petpooja; working relationships with Reelo, Razorpay, checkout.com, QueueBuster.",
      report: "Sales, order value per location, per-kiosk uptime against mall hours. It looked healthy while the same store broke three times in eleven weeks and refunds sat open for weeks. Taco Bell renewed in August and terminated in December. The report should have carried the open-complaint list and the age of every unresolved refund.",
    },
  },
  "buyer-app-plg": {
    w: 900,
    h: 420,
    nodes: [
      { id: "install", label: "Install", sub: "Meta ad or WhatsApp link", x: 30, y: 40, kind: "human" },
      { id: "otp", label: "Number → OTP", sub: "auto-fires; no signup form after", x: 250, y: 40, kind: "guard" },
      { id: "lang", label: "Language from state", sub: "DB trigger, not a popup", x: 470, y: 40, kind: "guard" },
      { id: "home", label: "Home", sub: "₹1 deals · combos · free gifts", x: 690, y: 40, kind: "ui" },
      { id: "card", label: "Product card", sub: "price on the card · slab strip", x: 690, y: 180, kind: "ui" },
      { id: "cart", label: "Cart", sub: "89% sat below MOV", x: 470, y: 180, kind: "store" },
      { id: "mov", label: "First-order MOV ₹300", sub: "computed field, zero UI change", x: 250, y: 180, kind: "guard" },
      { id: "review", label: "Pre-placement review", sub: "uncheck = save for later", x: 250, y: 320, kind: "guard" },
      { id: "order", label: "Order", sub: "250+ a day at the June peak", x: 30, y: 320, kind: "store" },
      { id: "crm", label: "Notification CRM", sub: "31 use cases · 8–10/day cap", x: 470, y: 320, kind: "service" },
      { id: "expiry", label: "7-day cart expiry", sub: "consecutive inactivity", x: 690, y: 320, kind: "guard" },
    ],
    edges: [
      { from: "install", to: "otp" },
      { from: "otp", to: "lang" },
      { from: "lang", to: "home" },
      { from: "home", to: "card" },
      { from: "card", to: "cart", label: "add" },
      { from: "cart", to: "mov" },
      { from: "mov", to: "review", label: "cleared" },
      { from: "review", to: "order" },
      { from: "cart", to: "crm", dashed: true, label: "blocked → nudge" },
      { from: "crm", to: "home", dashed: true, label: "“apni cart puri karo”" },
      { from: "cart", to: "expiry", dashed: true },
    ],
    notes: {
      install: "Most new buyers arrived from Meta ads or a WhatsApp campaign link. About 80% of daily actives had never ordered.",
      otp: "OTP fires the moment a valid 10-digit number is typed, auto-login on verify, and the name-and-retailer-type screen that used to block the user after OTP is gone; the name is captured in the checkout address form instead. Specced 13 June, shipped 16 June.",
      lang: "Language is derived from the shop's state by a database trigger, Hindi belt → Hindi, South, East and metros → a thin toggle strip, and a manual choice is never overwritten. The full-screen language popup that dropped the first funnel step is gone.",
      home: "Tabs proposed in the July spec: ₹1 Deals | Combos | Free Gifts | Best Deals | Referral | Games, best-converting first. Buyers had told me the app was confusing to navigate.",
      card: "The final price shows on the card, not at checkout. Volume slabs became an inline “add 4 more units → ₹30 off” strip instead of a blocking modal; margin reframed as “extra earnings”.",
      cart: "38.5k live carts, 89% of all live carts, sat below minimum order value. People were not failing to find products; they were failing to clear a floor.",
      mov: "First-time buyers see a lower minimum via a computed field that shadows the MOV column, so the app needed no change. By mid-June the company set a flat ₹300 first-order MOV across brands.",
      review: "After Pay, a sheet lists exactly which deliveries are about to be placed. Unchecking one saves the seller for later rather than deleting it: the fix for “a second delivery got ordered without me realising”.",
      order: "Orders hit 250+ a day on 11 June 2026, an all-time high on the courier model, with DAU peaking near 9.8k the same fortnight. A stack of changes, not one lever.",
      crm: "The 31-use-case notification catalogue, led by MOV-blocked and payment-abandoned carts, with a hard cap of 8–10 pushes per buyer per day and a pipeline that reads a nightly snapshot rather than the live database.",
      expiry: "A draft cart is archived after seven consecutive days without a session; any session resets the streak. Draft rows outnumbered fulfilled orders ~10× before this, polluting every metric.",
    },
  },

  "doka": {
    w: 900,
    h: 400,
    nodes: [
      { id: "pitch", label: "Cold pitch", sub: "Figma prototype + video demo, Feb 2025", x: 30, y: 40, w: 200, kind: "service" },
      { id: "client", label: "DOKA Bakery House", sub: "9 branches, Riyadh", x: 290, y: 150, kind: "human" },
      { id: "price", label: "Scope & price", sub: "$6,400 → $7,000 · client asked $8,000", x: 30, y: 180, w: 200, kind: "guard" },
      { id: "contract", label: "Contract", sub: "Saudi law · 40/40/20 · 10 Jun 2025", x: 30, y: 320, w: 200, kind: "store" },
      { id: "journeys", label: "Two journeys", sub: "Make My Cake vs ready-made", x: 510, y: 40, kind: "guard" },
      { id: "config", label: "Cake configurator", sub: "5 steps · 3-angle preview", x: 730, y: 40, kind: "ui" },
      { id: "pos", label: "POSIST", sub: "215 SKUs · 9 branch IDs", x: 730, y: 180, kind: "external" },
      { id: "status", label: "Weekly status", sub: "8 Sep: ~95%, unstable", x: 510, y: 180, kind: "ui" },
      { id: "apple", label: "App Store review", sub: "approved Dec 2025", x: 730, y: 320, kind: "external" },
      { id: "handover", label: "Handover", sub: "Jan–Feb 2026", x: 510, y: 320, kind: "store" },
    ],
    edges: [
      { from: "pitch", to: "client" },
      { from: "client", to: "price", label: "three rounds" },
      { from: "price", to: "contract" },
      { from: "client", to: "journeys", label: "requirements" },
      { from: "journeys", to: "config" },
      { from: "config", to: "pos", label: "menu mapping" },
      { from: "client", to: "status", label: "demos" },
      { from: "status", to: "apple", dashed: true, label: "build" },
      { from: "status", to: "handover", dashed: true },
    ],
    notes: {
      pitch: "The client had only ever bought kiosks from us. The pitch was a clickable prototype and a recorded demo, benchmarked openly against LOLA, the Saudi cake app they admired, rather than a proposal document.",
      client: "Herfy's cake sub-brand, nine branches on POSIST, a real 215-SKU catalogue priced in riyals. The coordinator, the business team and their finance director were all in the loop; the CEO signed.",
      price: "Phase 1 and 2 priced at $7,000 against an earlier $6,400 as loyalty, CRM and AI cake-image generation were added; when the client pushed to $8,000, scope was cut back to Phase 1 instead. AI image generation costed separately (~$1,000) and made optional.",
      contract: "Signed 10 June 2025 by both CEOs, reviewed by DOKA's finance director and legal, with a 40% advance and 40/40/20 milestones: advance, store deployment, third-party migration.",
      journeys: "Custom cakes ship next-day from one central kitchen; ready-made items same-day from the nearest branch. A unified cart broke order-status logic, so I put two named options to the client and asked them to choose rather than merging the flows silently.",
      config: "Shape and size, flavour, colour, decoration, personalisation, with a live preview from top, side and slice and a running SAR price. Colour rendered dynamically; the missing shape-and-flavour permutations generated with an image model.",
      pos: "I uploaded the store locations and 40% of the menu with its POSIST mapping myself when the client's assets slipped. Order sync integrated and UAT-tested, with event-sync issues still open at the September report.",
      status: "Weekly status to the client's coordinator; a signed ~25-item report on 8 September at “~95% of core functionalities”. At the 21 August demo, asked for a launch date, I said the app was unstable and needed significant testing.",
      apple: "Apple approved the iOS build for distribution in December 2025; the Android build was handed over on the client's own developer account.",
      handover: "When the client objected to the app and kiosk contracts being tied together, I executed a full transition, every asset handed over in January 2026, and closed the relationship on 24 February.",
    },
  },
  "pricing-experiments": {
    w: 900,
    h: 420,
    nodes: [
      { id: "shop", label: "Shopkeeper", sub: "buys on margin, not on price", x: 30, y: 180, kind: "human" },
      { id: "card", label: "Product card", sub: "price and margin shown here", x: 250, y: 60, kind: "ui" },
      { id: "item", label: "Item coupon", sub: "% rises with quantity", x: 470, y: 60, kind: "guard" },
      { id: "rupee", label: "₹1 trial item", sub: "10 products from 10 brands", x: 250, y: 300, kind: "store" },
      { id: "base", label: "Base price −2%", sub: "funded by the platform", x: 30, y: 300, kind: "guard" },
      { id: "cart", label: "Cart", sub: "one cart coupon on top", x: 470, y: 180, kind: "store" },
      { id: "check", label: "Server re-check", sub: "at checkout, every time", x: 690, y: 180, kind: "guard" },
      { id: "flat", label: "Conversion: flat", sub: "30% used a coupon · ~15% converted", x: 690, y: 300, w: 190, kind: "external" },
      { id: "repeat", label: "Repeat rate", sub: "₹1 first orders: 2–8 pts lower", x: 690, y: 40, kind: "external" },
    ],
    edges: [
      { from: "shop", to: "card" },
      { from: "card", to: "item", label: "add 4 more" },
      { from: "item", to: "cart" },
      { from: "shop", to: "rupee", dashed: true, label: "trial" },
      { from: "rupee", to: "cart" },
      { from: "base", to: "card" },
      { from: "cart", to: "check" },
      { from: "check", to: "flat", dashed: true },
      { from: "rupee", to: "repeat", dashed: true, label: "measured after" },
    ],
    notes: {
      shop: "A kirana owner does not buy on price, he buys on margin: what he pays against what he can sell it for. Every decision here is about which number he sees and when.",
      card: "The first item in my July specification: stop hiding discounts behind codes, put the real price and the margin on the card. A discount found at checkout did not influence the decision to add.",
      item: "Every eligible product carries its own coupon, with the percentage rising as quantity crosses thresholds snapped to case sizes, recalculated live. It replaced a modal that interrupted the add to cart with a keyboard. Shipped 17 July in version 8.212.0.",
      rupee: "Ten products, normally ₹50 to ₹150, repriced to ₹1. The point was getting an unknown brand into a shop that would never buy a full case. Pure configuration, no code.",
      base: "Instead of adding a platform margin then discounting it, we funded 2% off the base price and showed it as a plain lower price. The position was to sell about 4% below base and say so.",
      cart: "One cart-level coupon can sit on top of the item coupons. Vouchers work the same way but are private to one buyer, issued by a sales agent on a call or by the team after a bad experience.",
      check: "Every discount is re-validated on the server at checkout, because a price a client can calculate is a price a client can be wrong about. A ₹200 cart coupon was being abused by splitting orders until it was capped.",
      flat: "Coupon usage went from 2.9% to 29.5% of orders in three weeks and order-level conversion stayed at about 15%, with user-level conversion drifting from 2% to 1.7%. High usage is not impact.",
      repeat: "Queried afterwards: buyers whose first order contained a ₹1 item came back within 30 days 2 to 8 points less often than buyers whose first order did not. The trial bought an order, not a customer.",
    },
  },

  "rewards-retention": {
    w: 900,
    h: 400,
    nodes: [
      { id: "buyer", label: "Shopkeeper", sub: "one of ~2,000 receiving deliveries", x: 30, y: 170, kind: "human" },
      { id: "qps", label: "Monthly gift ladder", sub: "paid on a month of orders", x: 250, y: 40, kind: "service" },
      { id: "streak", label: "Daily login reward", sub: "₹10 a day for opening the app", x: 250, y: 170, kind: "service" },
      { id: "cash", label: "₹75 first-order credit", sub: "one-time, expires", x: 250, y: 300, kind: "service" },
      { id: "ref", label: "Referral", sub: "₹100 now, ₹50 on delivery", x: 470, y: 300, kind: "service" },
      { id: "win", label: "Re-order next month", sub: "50% against 19%", x: 690, y: 40, kind: "store" },
      { id: "rent", label: "Actives when it stopped", sub: "9,431 → 5,710", x: 690, y: 170, kind: "external" },
      { id: "unused", label: "₹4.57 Cr issued", sub: "0.06% spent on an order", x: 690, y: 300, kind: "external" },
      { id: "rm", label: "Relationship manager", sub: "named person for the group worth keeping", x: 470, y: 40, w: 190, kind: "guard" },
    ],
    edges: [
      { from: "buyer", to: "qps" },
      { from: "buyer", to: "streak" },
      { from: "buyer", to: "cash" },
      { from: "buyer", to: "ref", dashed: true },
      { from: "qps", to: "rm" },
      { from: "rm", to: "win" },
      { from: "streak", to: "rent", dashed: true },
      { from: "cash", to: "unused", dashed: true },
      { from: "ref", to: "unused", dashed: true, label: "2% referred anyone" },
    ],
    notes: {
      buyer: "The question behind all four rewards: which of them changes whether this shopkeeper orders again next month. I queried each one against repeat orders rather than against claims.",
      qps: "Spend a set amount in a calendar month on delivered orders and get a physical gift, from a brass figure at ₹3,000 up to an air fryer at ₹30,000 and a trip at ₹3,00,000. It pays on cumulative monthly value, so the reward and the behaviour are the same thing.",
      streak: "₹10 a day for opening the app, falling to ₹2 and climbing back if you miss a day. Built by the AI team. The database shows claims on nine days only, 17 to 25 June 2026.",
      cash: "A one-time ₹75 wallet credit for buyers who had never successfully ordered, with reminders and an expiry that claws back the unused balance.",
      ref: "The new shop gets ₹100 at signup because someone signing up needs a reason to finish. The referrer's ₹50 waits for a delivered order because the referrer is the one who can game it. Good design, poor result.",
      rm: "Gift qualifiers are 7 to 13% of delivered buyers and produce 31 to 44% of monthly order value, so they are worth a named person. Every buyer was assigned a relationship manager round-robin, backfilled to 1,465,882 records.",
      win: "Qualifiers re-order the next month at two and a half to three times the rate of everyone else, in every month from April to July. The most robust retention signal in anything I ran, and still an association rather than a proof, because there was no holdout.",
      rent: "Daily actives averaged 9,431 on the days the login reward was paying and 5,710 once claims stopped. Attention you pay for daily is rented, not earned.",
      unused: "609,245 buyers were credited ₹4.57 crore, 559,920 of them in one bulk run, and 342 spent it on an order. First orders per week did not move. 603,235 expiry debits followed in August.",
    },
  },

  "ono-product": {
    w: 900,
    h: 420,
    nodes: [
      { id: "customer", label: "Customer at the kiosk", sub: "mall food court", x: 30, y: 180, kind: "human" },
      { id: "type", label: "Dine in or take away", sub: "table number, or skip it", x: 240, y: 60, kind: "ui" },
      { id: "wa", label: "Phone number", sub: "bill goes to WhatsApp", x: 240, y: 190, kind: "ui" },
      { id: "menu", label: "Menu", sub: "categories, add-ons, size", x: 460, y: 60, kind: "ui" },
      { id: "offer", label: "Offer engine", sub: "₹1 item · buy-one-get-N", x: 460, y: 190, kind: "guard" },
      { id: "pay", label: "Payment", sub: "card · UPI · pay at counter", x: 460, y: 320, kind: "ui" },
      { id: "pos", label: "Point of sale", sub: "POSIST · Petpooja · GoFrugal · Rista", x: 690, y: 190, w: 190, kind: "external" },
      { id: "kitchen", label: "Kitchen ticket", sub: "order number to collect", x: 690, y: 60, kind: "service" },
      { id: "report", label: "Weekly client report", sub: "revenue, uptime, per store", x: 690, y: 320, kind: "store" },
    ],
    edges: [
      { from: "customer", to: "type" },
      { from: "type", to: "wa" },
      { from: "wa", to: "menu" },
      { from: "menu", to: "offer", label: "qualifying item" },
      { from: "offer", to: "pay" },
      { from: "pay", to: "pos", label: "order push" },
      { from: "pos", to: "kitchen" },
      { from: "pos", to: "report", dashed: true },
    ],
    notes: {
      customer: "The product is a web application running on a touchscreen in a mall, one instance per brand. It was live for Taco Bell, Herfy, Burger Singh, Pizza Wings, SVS Foods and Wow Momo among others, and all of it predates me.",
      type: "Dine in asks for a table number from a keypad; take away skips it. One store could not use table numbers at all, so I pushed for that requirement to be removed and tested the store without it.",
      wa: "The customer's number, so the bill arrives on WhatsApp. I wrote the message text, with different wording for dine in and take away, and later had a review link added as a third message.",
      menu: "Category rail, vegetarian toggle, item cards, and a customise sheet with add-ons, size and quantity. I specified the combo and modifier rules, and had the cheaper option in a modifier list made the default.",
      offer: "The part I wrote as a requirement rather than a bug report. A ₹1 product on a qualifying purchase had to be offered on the parent item, not depend on the point-of-sale menu, and had to disappear if the parent left the cart. And buy-one-get-one had to scale: it was giving one free drink no matter how many qualifying items were in the cart.",
      pay: "Card terminal, UPI, a payment machine, or pay at the counter. Some payments completed at the gateway and never reached the kitchen, so I filed a structured escalation to the provider with a real payment id attached rather than asking the developer to retry.",
      pos: "Each kiosk syncs to whatever system the restaurant already runs. For one of them I wrote the full request and callback contract, five cases covering a simple item, a combo, a coupon, packing charges and a multi-item order, and presented it to their engineering team.",
      kitchen: "The order reaches the kitchen and the customer gets a number to show at collection. When it did not reach the kitchen, that was the escalation above.",
      report: "For about five months I produced the weekly client report: revenue week on week and per store, region trend, biggest droppers, uptime per kiosk against mall hours, and later order value per store. When a report claimed 90 of 102 kiosks were active against the 79 of 82 I had verified, I rejected it.",
    },
  },
};
