// Declarative system diagrams, rendered by components/Diagram.tsx.
// Coordinates are in a 960-wide viewBox. `notes` is what the reader sees when
// they hover or tap a node — written as "what it does and why it exists".
// Amber (guard) boxes are the rules that hold when people or systems misbehave.

export type NodeKind = "agent" | "service" | "store" | "external" | "guard" | "human" | "ui" | "tool";

export type DNode = { id: string; label: string; sub?: string; x: number; y: number; w?: number; h?: number; kind: NodeKind };
export type DEdge = { from: string; to: string; label?: string; dashed?: boolean };
export type DiagramSpec = { w: number; h: number; nodes: DNode[]; edges: DEdge[]; notes: Record<string, string> };

export const diagrams: Record<string, DiagramSpec> = {
  "jit-pivot": {
    w: 900,
    h: 400,
    nodes: [
      { id: "retailer", label: "Shopkeeper", sub: "orders in the evening", x: 30, y: 170, kind: "human" },
      { id: "app", label: "Buyer app", sub: "single seller · no per-brand MOV", x: 240, y: 80, kind: "ui" },
      { id: "fee", label: "₹75 fee, waived ≥ ₹500", sub: "shipped as one flag", x: 240, y: 260, kind: "guard" },
      { id: "jit", label: "JIT console", sub: "one PO per brand, that night", x: 450, y: 170, kind: "service" },
      { id: "brands", label: "Brands", sub: "our vehicle collects next morning", x: 690, y: 40, kind: "external" },
      { id: "warehouse", label: "Own warehouse", sub: "receive · putaway · pick · pack", x: 690, y: 170, kind: "service" },
      { id: "fleet", label: "Own fleet", sub: "dispatch · doorstep", x: 690, y: 300, kind: "service" },
      { id: "breach", label: "Breach queue", sub: "3–4 day promise", x: 450, y: 320, kind: "guard" },
    ],
    edges: [
      { from: "retailer", to: "app" },
      { from: "app", to: "fee", label: "cart" },
      { from: "fee", to: "jit", label: "order" },
      { from: "jit", to: "brands", label: "PO per brand" },
      { from: "brands", to: "warehouse", label: "pickup" },
      { from: "warehouse", to: "fleet" },
      { from: "jit", to: "breach", dashed: true, label: "past target" },
      { from: "fleet", to: "retailer", dashed: true, label: "next-day delivery" },
    ],
    notes: {
      retailer: "A kirana owner in Delhi or Gurgaon. Before the pivot, a ₹900 basket across three brands was blocked by three separate ₹300 minimums. After it, one seller and no minimum.",
      app: "The buyer app became a single-seller marketplace — everything resolves to Badho Wholesale. Brand minimums disappeared from the cart entirely.",
      fee: "The replacement for per-brand minimums: a flat ₹75 delivery fee waived above ₹500, shipped as a single flag so a buyer can never end up with neither a minimum nor a fee. Set as a round number before I had the basket distribution — the median came in at ₹379, so it was set too high.",
      jit: "Just-in-time, literally. Orders arrive in the evening; the console consolidates one purchase order per brand and pushes it that night. We never hold stock. This is the piece the operating document specified step by step.",
      brands: "The same brands we used to forward orders to. Now they are suppliers, and their minimum is met at our volume where it is trivial.",
      warehouse: "Layout and zoning, inbound receiving and putaway, pick-pack-dispatch, and the exception path when a brand short-ships — all written before the first delivery. Twelve days from document to first order.",
      fleet: "Our own vehicles, with driver allocation from the delivery-as-a-service stack. Serviceability was deliberately cut to two cities: density is the whole model.",
      breach: "Every order is checked against the delivery promise. In the final weeks it showed 53 orders past target, the oldest 16 days, and a 22% rejection rate. That was the live problem when the company stopped.",
    },
  },

  "contribution-turnaround": {
    w: 900,
    h: 420,
    nodes: [
      { id: "order", label: "Courier order", sub: "₹708, 4.3 kg, zone E: ₹282 freight", x: 30, y: 180, w: 190, kind: "store" },
      { id: "courier", label: "3PL courier", sub: "reweighs, charges the difference", x: 280, y: 40, kind: "external" },
      { id: "claims", label: "Claims service", sub: "24h window · sorter photo as proof", x: 500, y: 40, kind: "service" },
      { id: "dedupe", label: "De-dupe guard", sub: "every open ticket on the waybill", x: 720, y: 40, kind: "guard" },
      { id: "ledger", label: "Freight ledger", sub: "cost captured per order", x: 280, y: 180, kind: "store" },
      { id: "returns", label: "Returns stack", sub: "prepaid-only · address check · promise", x: 500, y: 180, w: 190, kind: "guard" },
      { id: "retailer", label: "Shopkeeper", sub: "reminder call · doorstep triage", x: 720, y: 180, kind: "human" },
      { id: "brand", label: "Brand statement", sub: "line-item deductions, not a mystery", x: 280, y: 320, kind: "ui" },
      { id: "pnl", label: "Contribution / order", sub: "−₹196 → +₹36", x: 500, y: 320, kind: "store" },
    ],
    edges: [
      { from: "order", to: "courier" },
      { from: "courier", to: "claims", label: "weight discrepancy" },
      { from: "claims", to: "dedupe" },
      { from: "dedupe", to: "courier", dashed: true, label: "claim filed" },
      { from: "order", to: "ledger" },
      { from: "ledger", to: "brand" },
      { from: "order", to: "returns", label: "on delivery attempt" },
      { from: "returns", to: "retailer" },
      { from: "ledger", to: "pnl" },
      { from: "returns", to: "pnl", dashed: true, label: "RTO 42.6% → 21.4%" },
    ],
    notes: {
      order: "The order that framed the problem: ₹708.50 of goods, ₹282 of freight plus ₹25.50 COD fee — roughly 43% of order value spent shipping it.",
      courier: "Third-party couriers on the intercity model. They systematically reweighed parcels and billed the difference; every one of those was recoverable, but only inside a 24-hour priority window.",
      claims: "Detects the weight discrepancy, checks nobody has already raised it, and files the claim with the courier's own sorter photograph as evidence. 378 claims and 362 tickets on one representative day. Built by the automation team to my requirement.",
      dedupe: "The guard rail: de-duplicates against every open ticket on that waybill, not just its own, so it can never double-file on top of a human. Judgement stayed with people; the deadline went to a system.",
      ledger: "Courier cost, handling and weight deductions captured per order. You cannot fix a cost nobody can see.",
      returns: "Automatic prepaid-only after a single return (reinstatement by manual review), address validation at checkout, a zone-wise delivery promise paying ₹50 when missed, doorstep-refusal triage, reminder calls on the day. 34 of 42 fulfilment features were specced by me.",
      retailer: "The person whose parcel took 28 days at the p90 in January and 10 days by June. He does not experience a median.",
      brand: "Brands see deductions as a line-item breakup instead of unexplained numbers on a settlement. Disputes drop when the cost is legible.",
      pnl: "Company P&L per completed order — not my measurement, I drove the programme underneath. Feb −₹196, Apr −₹25, Jun −₹18, Jul +₹36. Net loss including returns: −₹5.2 L in June, −₹0.24 L in July.",
    },
  },

  "whatsapp-channel": {
    w: 900,
    h: 440,
    nodes: [
      { id: "base", label: "Buyer base", sub: "1,167,517 people", x: 30, y: 30, kind: "store" },
      { id: "waterfall", label: "Cohort waterfall", sub: "7 rules · first match wins", x: 250, y: 30, kind: "service" },
      { id: "gate", label: "Serviceability gate", sub: "pincode inner-join before any send", x: 470, y: 30, kind: "guard" },
      { id: "router", label: "Template router", sub: "utility vs marketing · ~7× gap", x: 470, y: 170, kind: "guard" },
      { id: "sender", label: "Self-hosted sender", sub: "₹0.145 → ₹0.115 a message", x: 250, y: 170, kind: "service" },
      { id: "meta", label: "Meta WhatsApp API", sub: "the platform we now talk to directly", x: 30, y: 170, kind: "external" },
      { id: "retailer", label: "Shopkeeper", sub: "taps, or sends a photo of a list", x: 30, y: 320, kind: "human" },
      { id: "app", label: "Buyer app", sub: "deep link or Play Store install", x: 250, y: 320, kind: "ui" },
      { id: "attribution", label: "Attribution rule", sub: "same-day, not seven-day", x: 470, y: 320, kind: "guard" },
      { id: "report", label: "July report", sub: "1.12× on GMV · 13% take rate", x: 690, y: 320, kind: "ui" },
      { id: "agent", label: "Sales agent", sub: "cannot place orders", x: 690, y: 170, kind: "agent" },
    ],
    edges: [
      { from: "base", to: "waterfall" },
      { from: "waterfall", to: "gate" },
      { from: "gate", to: "router" },
      { from: "router", to: "sender" },
      { from: "sender", to: "meta" },
      { from: "meta", to: "retailer", label: "message" },
      { from: "retailer", to: "app", label: "click" },
      { from: "app", to: "attribution", label: "open / install" },
      { from: "attribution", to: "report" },
      { from: "retailer", to: "agent", dashed: true, label: "photo of a list" },
    ],
    notes: {
      base: "Every buyer who ever signed up, installed or ordered. Most of them never ordered, which is why the never-ordered pool is banded by how long they have been gone — down to the 73,473 who installed and never opened the app.",
      waterfall: "Each person lands in exactly one of seven cohorts, first matching rule wins, so the set is mutually exclusive and exhaustive by construction. A live cart outranks a past order.",
      gate: "Messaging someone we cannot deliver to spends money and template quota to annoy them. Every cohort is inner-joined to pincode serviceability first.",
      router: "Meta prices a utility template far below a marketing one — ₹2,885 for 19,894 utility sends versus ₹16,811 for 15,423 marketing sends on one campaign. Routing transactional traffic correctly was the larger half of the saving. When Meta rescanned and reclassified 15,398 conversations, it cost ₹14,551.",
      sender: "We were paying a vendor ₹0.145 a message to sit in front of Meta's own API. Moving in-house took it to ₹0.115 on ~169,000 messages a month, and removed a dependency that had already cut us off once over an unpaid invoice.",
      meta: "The WhatsApp Business platform itself. Its template categories and rescans are the variable cost you do not control.",
      retailer: "Many shopkeepers would not tap a link at all. They photographed a handwritten order or typed it in Hinglish — wonderful intent, impossible to scale with two people on a desk.",
      app: "The app already normalised both entry paths — deep link and fresh install — into one field. Our queries were reading the other one, so 117 buyers were visible out of 537 real.",
      attribution: "Credit an order only if the WhatsApp touch was the same day. The seven-day window gave 1,272 orders and 5.22×; same-day gave 647 and 2.60×. I led with the smaller number and wrote down that the truth sits between them.",
      report: "The paragraph at the top: at 1.12× the channel only breaks even if the take rate clears 89%. Ours was 13–15%. The channel lost money in July, and the report said so on its front page.",
      agent: "The first working version was mine — orchestrator, prompt layer, messaging, auth and policy engine, committed in one sitting with a handover document. The AI pod owned it from day three. It is blocked from placing orders at the tool layer, so it can never claim to have placed one.",
    },
  },

  "move-it-daas": {
    w: 900,
    h: 400,
    nodes: [
      { id: "distributor", label: "Distributor", sub: "has paper bills, not a system", x: 30, y: 170, kind: "human" },
      { id: "ocr", label: "OCR intake", sub: "bill photo → delivery task", x: 250, y: 60, kind: "agent" },
      { id: "booking", label: "Booking", sub: "seller app · price per vehicle class", x: 250, y: 280, kind: "ui" },
      { id: "assign", label: "Assignment", sub: "vehicle + driver", x: 470, y: 170, kind: "service" },
      { id: "route", label: "Routed stops", sub: "own route model since May", x: 690, y: 40, kind: "service" },
      { id: "otp", label: "Two-party OTP", sub: "every handover", x: 690, y: 170, kind: "guard" },
      { id: "cash", label: "Cash custody", sub: "buyer → driver → hub → settlement", x: 690, y: 300, w: 180, kind: "guard" },
      { id: "exceptions", label: "Named exceptions", sub: "closed list · countable", x: 470, y: 300, kind: "store" },
    ],
    edges: [
      { from: "distributor", to: "ocr", label: "photo" },
      { from: "distributor", to: "booking" },
      { from: "ocr", to: "assign" },
      { from: "booking", to: "assign" },
      { from: "assign", to: "route" },
      { from: "route", to: "otp" },
      { from: "otp", to: "cash", label: "COD" },
      { from: "assign", to: "exceptions", dashed: true, label: "failure" },
    ],
    notes: {
      distributor: "Already a Badho customer for groceries; not a customer for logistics. Solving delivery with ad-hoc vehicles, informal cash and no proof of delivery. Launch cohort: 128 sellers in Gurgaon.",
      ocr: "The go-to-market in one decision: an order enters as a photograph of a handwritten bill and is read into a structured task. We met the customer where he was instead of asking him to adopt a system first.",
      booking: "3-wheeler ₹1,600, 4-wheeler ₹2,000. Priced by vehicle class rather than distance because a distributor planning a day wants a number he can commit to, not a meter running.",
      assign: "The system assigns a vehicle and a driver. A V3 with automated allocation and driver ranking was feature-complete by early September and never demonstrated running — the company wound down first.",
      route: "The first version leaned on a third-party routing partner; we replaced it with our own route model in May.",
      otp: "Every handover confirmed by an OTP both parties hold. Proof of delivery stops being an argument.",
      cash: "Cash on the round is tracked through three recorded transfers, so at no point is money simply trusted. A shortfall becomes findable rather than a rumour.",
      exceptions: "Failures are a closed taxonomy, not free text — which is what makes them countable and therefore fixable.",
    },
  },

  "vernacular-search": {
    w: 900,
    h: 400,
    nodes: [
      { id: "shopkeeper", label: "Shopkeeper", sub: "“sarso tel” · “all out” · “meggi”", x: 30, y: 170, kind: "human" },
      { id: "search", label: "Search", sub: "Hindi labels at equal weight", x: 250, y: 170, kind: "service" },
      { id: "rank", label: "Exact-first ranking", sub: "then looser · popularity breaks ties", x: 470, y: 40, kind: "guard" },
      { id: "synonyms", label: "Synonym table", sub: "699,684 rows on 32,536 roots", x: 470, y: 250, kind: "store" },
      { id: "catalogue", label: "Catalogue titles", sub: "“Fortune Kachi Ghani … 1L Pouch”", x: 690, y: 40, kind: "store" },
      { id: "generator", label: "Synonym generator", sub: "LLM · four categories", x: 690, y: 170, kind: "agent" },
      { id: "precision", label: "Stay-specific rule", sub: "toor dal → arhar dal, not dal", x: 690, y: 300, kind: "guard" },
      { id: "events", label: "Search events", sub: "what buyers actually typed", x: 250, y: 320, kind: "store" },
    ],
    edges: [
      { from: "shopkeeper", to: "search", label: "query" },
      { from: "search", to: "rank" },
      { from: "search", to: "synonyms", label: "expands" },
      { from: "catalogue", to: "generator" },
      { from: "generator", to: "precision" },
      { from: "precision", to: "synonyms" },
      { from: "search", to: "events" },
      { from: "events", to: "generator", dashed: true, label: "learning loop" },
    ],
    notes: {
      shopkeeper: "Tier-2 and tier-3 kirana owners typing Hindi in Roman script, phonetically, with typos, and by brand rather than product. A competitor's brand name is often the category name in their head.",
      search: "The product search after a third-party vendor was ripped out seven weeks in. Hindi labels are indexed at equal weight to English so the multilingual catalogue work feeds search directly.",
      rank: "A shopkeeper restocking a known item wants that item, not a helpful selection of similar ones. Exact match first, then progressively looser, popularity as the tie-break.",
      synonyms: "The asset: 699,684 synonyms on 32,536 root words, 21.5 per concept. A static list would have been a fraction of that and would have aged.",
      catalogue: "Messy product titles reduced by a language model to their core unit — pack size is noise, but packaging that is the product (a jute bag) must survive.",
      generator: "Transliterations (jeera → cumin), colloquial trade terms (“kachua chap” → mosquito coils), phonetic typos (biskut), and genericised brands (surf → detergent). The fourth is the commercial one: a competitor's brand finds our stock.",
      precision: "One rule stops the layer collapsing into mush. An early version matched hair oil to motor oil; the fix was a tighter prompt and an accuracy pass, not more fuzziness.",
      events: "Every real search emits an event. The words the shopkeeper typed feed back into the generator, so the vocabulary compounds and the terms we never thought of arrive on their own. What I did not instrument: the zero-result rate before the work started.",
    },
  },

  "restaurant-tech-gtm": {
    w: 900,
    h: 400,
    nodes: [
      { id: "outbound", label: "Outbound", sub: "60+ brands · cold email · Apollo", x: 30, y: 40, kind: "service" },
      { id: "pricing", label: "Pricing architecture", sub: "rent or own · per kiosk / store / chain", x: 30, y: 200, w: 190, kind: "store" },
      { id: "chain", label: "Restaurant chain", sub: "Taco Bell · Herfy · DOKA", x: 270, y: 120, kind: "human" },
      { id: "contract", label: "Contract & redlines", sub: "six of seven accepted", x: 490, y: 30, kind: "guard" },
      { id: "renewal", label: "Renewal", sub: "110 → 112 SAR · 17.65% gross-up", x: 710, y: 30, kind: "store" },
      { id: "estate", label: "Kiosk estate", sub: "34 + 79 live kiosks", x: 490, y: 160, kind: "ui" },
      { id: "pos", label: "POS partners", sub: "Petpooja · GoFrugal · POSIST", x: 710, y: 160, kind: "external" },
      { id: "report", label: "Weekly report", sub: "revenue · uptime — and what it missed", x: 490, y: 300, kind: "ui" },
    ],
    edges: [
      { from: "outbound", to: "chain" },
      { from: "pricing", to: "chain", label: "proposal" },
      { from: "chain", to: "contract" },
      { from: "contract", to: "renewal" },
      { from: "chain", to: "estate", label: "go-live" },
      { from: "estate", to: "pos", label: "price sync" },
      { from: "estate", to: "report" },
      { from: "report", to: "chain", dashed: true, label: "weekly" },
    ],
    notes: {
      outbound: "Where I started in January 2024: cold email, LinkedIn and WhatsApp outreach, demo booking, an Apollo lead database, two junior interns from April. Sixty-plus brands reached; a handful became paying clients.",
      pricing: "Subscription (₹35,000 setup, ₹1,500–2,500 per kiosk per month) against an ownership buyout (₹2.5–2.75 lakh, client owns the code); enterprise by store count at ₹4–5 lakh a month. Authored for seven QSR brands.",
      chain: "Taco Bell India (34 kiosks, 19 malls, eleven store mailboxes escalating to me directly), Herfy in Saudi Arabia (79 kiosks, inherited, defended through three renewals), DOKA in Riyadh (nine branches, cold-pitched and signed at ~$7,000).",
      contract: "Herfy's counsel returned seven changes. I accepted six that cost nothing and refused the one that split billing into two cycles, because we funded infrastructure upfront against that invoice. The six concessions are what made the refusal credible.",
      renewal: "A two-riyal rise after fifteen months at 110: anchor on the absolute change, show the cost absorbed, benchmark the 5–10% norm, concede from your own opening. The 15% withholding-tax dispute resolved by grossing the invoice up 17.65%, the figure that leaves the net whole.",
      estate: "The live kiosks I was responsible for keeping up: promotional go-lives, refunds order by order, invoices issued and voided, the payment-reminder feature specified and shipped.",
      pos: "Integrations are how a small software company reaches chains it cannot sell to directly. Formal registrations with GoFrugal and Petpooja; working relationships with Reelo, Razorpay, checkout.com, QueueBuster.",
      report: "Sales, order value per location, per-kiosk uptime against mall hours. It looked healthy while the same store broke three times in eleven weeks and refunds sat open for weeks. Taco Bell renewed in August and terminated in December. The report should have carried the open-complaint list and the age of every unresolved refund.",
    },
  },
};
